import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Logo from '../public/logo.svg'
import Play from '../public/play.svg' 
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <>
      <Head>
        <title>Direção-C Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.banner}>
      <Image
            className={styles.logo}
            src={Logo}
            alt="Logo da Direção Concursos - Uma águia branca sob fundo preto"
            width={100}
            height={37}
            priority
          />
          <div className={styles.play}>
            <Image
              src={Play}
              alt="Play"
              width={25}
              height={20}
              priority
            />
          </div>
      </div>

      <div className={styles.container}>
      </div>
             </>
  )
}
