import { useState } from 'react';
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Player from '../components/Player';
import Banner from '../components/Banner'
import Queue from '../components/Queue'
import TestQueue from '../data/test-queue.json'


export default function Home() {
  const [videoData, updateVideoData] = useState(TestQueue.items);
  const [currentVideoId, updateCurrentVideoId] = useState(videoData[0].id.videoId)

  const playNext = () => {
    videoData.shift()
    if (videoData.length > 0) {
      updateCurrentVideoId(videoData[0].id.videoId)
    }
  }

  return (
    <>
      <Head>
        <title>Direção-C Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Banner />

      <div className={styles.container}>
        <Player videoURL={currentVideoId} onEnd={playNext}/>
        <Queue data={videoData} />
      </div>

      <footer className={styles.footer}>
        <a href="https://direcaoconcursos.com.br" target="_blank" rel="noopener noreferrer">
          Direção Concursos
        </a>
      </footer>
      </main>
</>
  )
}
